config/account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('edit/', views.edit, name='edit'),
    path('profile', views.profile, name='profile')
]

config/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove,name='cart_remove'),
]

config/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('account/', include('account.urls', namespace='account')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'

urlpatterns = [
     path('', views.product_list, name='product_list'),
     path('search/', views.post_search, name='post_search'),
     path('<slug:category_slug>/', views.product_list,
         name='product_list_by_category'),
     path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
]

config/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name']),]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
    decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])
    

config/shop/forms.py
from django import forms

class SearchForm(forms.Form):
 query = forms.CharField()

config/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from cart.forms import CartAddProductForm
from django.contrib.postgres.search import SearchVector,SearchQuery, SearchRank
from .forms import SearchForm


def product_list(request, category_slug=None):
    """
    Create Catalog.
    """
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category,slug=category_slug)
    products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    """
    Show 1 product.
    """
    product = get_object_or_404(Product,id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,
                   'cart_product_form': cart_product_form})


def post_search(request):
    """
    Create simple search with Postgresql.
    """
    form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            search_vector = SearchVector('name')
            search_query = SearchQuery(query)
            results = Product.objects.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query)
            ).filter(search=search_query).order_by('-rank')
    return render(request,
                  'shop/search.html',
                  {'form': form,
                   'query': query,
                   'results': results})

config/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>{% block title %}My shop{% endblock %}</title>
        <link href="{% static "css/base.css" %}" rel="stylesheet">
    </head>
    <body>
        <div id="header">
            <a href='{% url "shop:product_list" %}' class="logo">My shop</a>
        </div>
        <div id="subheader">
            <div class="cart">
                {% with total_items=cart|length %}
                    {% if total_items > 0 %}
                        Your cart:
                        <a href="{% url "cart:cart_detail" %}">
                            {{ total_items }} item{{ total_items|pluralize }},
                            ${{ cart.get_total_price }}
                        </a>
                    {% elif not order %}
                        Your cart is empty.
                    {% endif %}
                {% endwith %}
            </div>
            <span class="user">
                {% if request.user.is_authenticated %}
                    Hello {{ request.user.first_name|default:request.user.username }},
                    <form action="{% url 'logout' %}" method="post">
                        {% csrf_token %} 
                        <button type="submit">Logout</button>
                    </form
                {% else %}
                    <a href="{% url "login" %}">Log-in</a>
                {% endif %}
            </span>
                <a href="{% url 'account:profile' %}">Profile</a>
                <a href="{% url 'shop:post_search' %}">Search</a>
        </div>
        <div id="content">
        {% block content %}
        {% endblock %}
        </div>
    </body>
</html>

config/shop/templates/shop/search.html
{% extends "shop/base.html" %}

{% block title %}Search{% endblock %}

{% block content %}
  {% if query %}
    <h1>Announcement containing words "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
        Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for product in results %}
      <a href="{{ product.get_absolute_url }}">
        {{product.name}}<br>
      </a>
      <p>
        {{product.name|truncatewords:15|linebreaks}}
      </p>
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url "shop:post_search" %}">Search again</a></p>
  {% else %}
    <h1>Search products</h1>
    <form method="get">
      {{ form.as_p }}
      <input type="submit" value="Search">
    </form>
  {% endif %}
{% endblock %}